import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppThemeContextProvider } from "./context/AppThemeContext";
import AppBar from "./component/AppBar";
import ReduxProvider from "./redux/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//metadata is used in server component
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Next Awesome App",
  description: "List of Customer",
  keywords: "Customers, Online Store, React, Next"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}> 
      <ReduxProvider>
          <AppThemeContextProvider>
          <body className="min-h-full flex flex-col">
              <header>
              <AppBar/>
              </header>
              <main>{children}</main> 
          </body>
      </AppThemeContextProvider>
        </ReduxProvider>
    </html>
  );
}
